language: php

sudo: false

php:
- 5.5
- 5.6
- 7.0
- hhvm

matrix:
  allow_failures:
    - php: hhvm
  include:
    - php: 5.5
      env: WP_VERSION=4.6

before_script:
  - composer self-update --no-interaction
  - composer install --no-interaction
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script:
  - phpunit
  - vendor/bin/phpcs --standard=phpcs.xml